//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Points {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Points.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1950,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;British Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Nino&quot;,&quot;FamilyName&quot;:&quot;Farina&quot;,&quot;Name&quot;:&quot;Nino Farina&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Nino_Farina&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Alfa Romeo&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One&quot;},&quot;FastestLap&quot;:true},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Luigi&quot;,&quot;FamilyName&quot;:&quot;Fagioli&quot;,&quot;Name&quot;:&quot;Luigi Fagioli&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1950 {
            get {
                return ResourceManager.GetString("1950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1951,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Swiss Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Juan&quot;,&quot;FamilyName&quot;:&quot;Fangio&quot;,&quot;Name&quot;:&quot;Juan Fangio&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Juan_Manuel_Fangio&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Alfa Romeo&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One&quot;}},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Piero&quot;,&quot;FamilyName&quot;:&quot;Taruffi&quot;,&quot;Name&quot;:&quot;Piero Taruffi&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Piero_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1951 {
            get {
                return ResourceManager.GetString("1951", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1952,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Swiss Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Piero&quot;,&quot;FamilyName&quot;:&quot;Taruffi&quot;,&quot;Name&quot;:&quot;Piero Taruffi&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Piero_Taruffi&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Ferrari&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Scuderia_Ferrari&quot;}},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Rudi&quot;,&quot;FamilyName&quot;:&quot;Fischer&quot;,&quot;Name&quot;:&quot;Rudi Fischer&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Rudi_Fischer&quot;},&quot;Constr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1952 {
            get {
                return ResourceManager.GetString("1952", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1953,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Argentine Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Alberto&quot;,&quot;FamilyName&quot;:&quot;Ascari&quot;,&quot;Name&quot;:&quot;Alberto Ascari&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Alberto_Ascari&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Ferrari&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Scuderia_Ferrari&quot;}},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Luigi&quot;,&quot;FamilyName&quot;:&quot;Villoresi&quot;,&quot;Name&quot;:&quot;Luigi Villoresi&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Luigi_Vil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1953 {
            get {
                return ResourceManager.GetString("1953", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1954,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Argentine Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Juan&quot;,&quot;FamilyName&quot;:&quot;Fangio&quot;,&quot;Name&quot;:&quot;Juan Fangio&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Juan_Manuel_Fangio&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Maserati&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Maserati&quot;}},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Nino&quot;,&quot;FamilyName&quot;:&quot;Farina&quot;,&quot;Name&quot;:&quot;Nino Farina&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Nino_Farina&quot;},&quot;Constructor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1954 {
            get {
                return ResourceManager.GetString("1954", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1955,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Argentine Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Juan&quot;,&quot;FamilyName&quot;:&quot;Fangio&quot;,&quot;Name&quot;:&quot;Juan Fangio&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Juan_Manuel_Fangio&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Mercedes&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One&quot;}},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;José Froilán&quot;,&quot;FamilyName&quot;:&quot;González&quot;,&quot;Name&quot;:&quot;José Froilán González&quot;,&quot;Url&quot;:&quot;http://en.wikip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1955 {
            get {
                return ResourceManager.GetString("1955", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1956,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Argentine Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Luigi&quot;,&quot;FamilyName&quot;:&quot;Musso&quot;,&quot;Name&quot;:&quot;Luigi Musso&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Luigi_Musso&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Ferrari&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Scuderia_Ferrari&quot;}},{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Juan&quot;,&quot;FamilyName&quot;:&quot;Fangio&quot;,&quot;Name&quot;:&quot;Juan Fangio&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Juan_Manuel_Fangio&quot;},&quot;Cons [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1956 {
            get {
                return ResourceManager.GetString("1956", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1957,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Argentine Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Juan&quot;,&quot;FamilyName&quot;:&quot;Fangio&quot;,&quot;Name&quot;:&quot;Juan Fangio&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Juan_Manuel_Fangio&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Maserati&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Maserati&quot;}},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Jean&quot;,&quot;FamilyName&quot;:&quot;Behra&quot;,&quot;Name&quot;:&quot;Jean Behra&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Jean_Behra&quot;},&quot;Constructor&quot;:{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1957 {
            get {
                return ResourceManager.GetString("1957", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1958,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Argentine Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Stirling&quot;,&quot;FamilyName&quot;:&quot;Moss&quot;,&quot;Name&quot;:&quot;Stirling Moss&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Stirling_Moss&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Cooper&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Cooper_Car_Company&quot;}},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Luigi&quot;,&quot;FamilyName&quot;:&quot;Musso&quot;,&quot;Name&quot;:&quot;Luigi Musso&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Luigi_Musso&quot;},&quot;Cons [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1958 {
            get {
                return ResourceManager.GetString("1958", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Season&quot;:1959,&quot;Races&quot;:[{&quot;RaceName&quot;:&quot;Monaco Grand Prix&quot;,&quot;Results&quot;:[{&quot;Position&quot;:1,&quot;PositionText&quot;:&quot;1&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Jack&quot;,&quot;FamilyName&quot;:&quot;Brabham&quot;,&quot;Name&quot;:&quot;Jack Brabham&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Jack_Brabham&quot;},&quot;Constructor&quot;:{&quot;Name&quot;:&quot;Cooper-Climax&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Cooper_Car_Company&quot;}},{&quot;Position&quot;:2,&quot;PositionText&quot;:&quot;2&quot;,&quot;Finished&quot;:true,&quot;Driver&quot;:{&quot;GivenName&quot;:&quot;Tony&quot;,&quot;FamilyName&quot;:&quot;Brooks&quot;,&quot;Name&quot;:&quot;Tony Brooks&quot;,&quot;Url&quot;:&quot;http://en.wikipedia.org/wiki/Tony_Brooks&quot;},&quot;Con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1959 {
            get {
                return ResourceManager.GetString("1959", resourceCulture);
            }
        }
    }
}
