//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGetter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiGetter.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;MRData&quot;:{&quot;xmlns&quot;:&quot;http:\/\/ergast.com\/mrd\/1.4&quot;,&quot;series&quot;:&quot;f1&quot;,&quot;url&quot;:&quot;http://ergast.com/api/f1/1950.json&quot;,&quot;limit&quot;:&quot;30&quot;,&quot;offset&quot;:&quot;0&quot;,&quot;total&quot;:&quot;7&quot;,&quot;RaceTable&quot;:{&quot;season&quot;:&quot;1950&quot;,&quot;Races&quot;:[{&quot;season&quot;:&quot;1950&quot;,&quot;round&quot;:&quot;1&quot;,&quot;url&quot;:&quot;http:\/\/en.wikipedia.org\/wiki\/1950_British_Grand_Prix&quot;,&quot;raceName&quot;:&quot;British Grand Prix&quot;,&quot;Circuit&quot;:{&quot;circuitId&quot;:&quot;silverstone&quot;,&quot;url&quot;:&quot;http:\/\/en.wikipedia.org\/wiki\/Silverstone_Circuit&quot;,&quot;circuitName&quot;:&quot;Silverstone Circuit&quot;,&quot;Location&quot;:{&quot;lat&quot;:&quot;52.0786&quot;,&quot;long&quot;:&quot;-1.01694&quot;,&quot;locality&quot;:&quot;Silverston [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1950Season {
            get {
                return ResourceManager.GetString("1950Season", resourceCulture);
            }
        }
    }
}
